### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by hoyeunglee** [CoqEAL/CoqEAL#1]
export COQBIN=/usr/bin/
export SSRSRC=/home/martin/geo/CoqEAL/theory
export SSRLIB=/home/martin/geo/CoqEAL

nd in loadpath!
**\* Warning: in file boolF2.v, library ssrbool.v is required and has not been found in loadpath!
**\* Warning: in file boolF2.v, library eqtype.v is required and has not been found in loadpath!
**\* Warning: in file boolF2.v, library ssrnat.v is required and has not been found in loadpath!
**\* Warning: in file boolF2.v, library seq.v is required and has not been found in loadpath!
**\* Warning: in file boolF2.v, library div.v is required and has not been found in loadpath!
**\* Warning: in file boolF2.v, library choice.v is required and has not been found in loadpath!
**\* Warning: in file boolF2.v, library fintype.v is required and has not been found in loadpath!
**\* Warning: in file boolF2.v, library bigop.v is required and has not been found in loadpath!
**\* Warning: in file boolF2.v, library finset.v is required and has not been found in loadpath!
**\* Warning: in file boolF2.v, library prime.v is required and has not been found in loadpath!
**\* Warning: in file boolF2.v, library fingroup.v is required and has not been found in loadpath!
**\* Warning: in file boolF2.v, library ssralg.v is required and has not been found in loadpath!
**\* Warning: in file boolF2.v, library zmodp.v is required and has not been found in loadpath!
**\* Warning: in file boolF2.v, library finalg.v is required and has not been found in loadpath!
/usr/bin/coqdep -c -slash -I .  "strassen.v" > "strassen.v.d" || ( RV=$?; rm -f "strassen.v.d"; exit ${RV} )
**\* Warning: in file strassen.v, library Ncring.v is required and has not been found in loadpath!
**\* Warning: in file strassen.v, library Ncring_tac.v is required and has not been found in loadpath!
**\* Warning: in file strassen.v, library ssreflect.v is required and has not been found in loadpath!
**\* Warning: in file strassen.v, library ssrbool.v is required and has not been found in loadpath!
**\* Warning: in file strassen.v, library ssrfun.v is required and has not been found in loadpath!
**\* Warning: in file strassen.v, library eqtype.v is required and has not been found in loadpath!
**\* Warning: in file strassen.v, library ssrnat.v is required and has not been found in loadpath!
**\* Warning: in file strassen.v, library seq.v is required and has not been found in loadpath!
**\* Warning: in file strassen.v, library choice.v is required and has not been found in loadpath!
**\* Warning: in file strassen.v, library fintype.v is required and has not been found in loadpath!
**\* Warning: in file strassen.v, library div.v is required and has not been found in loadpath!
**\* Warning: in file strassen.v, library finfun.v is required and has not been found in loadpath!
**\* Warning: in file strassen.v, library bigop.v is required and has not been found in loadpath!
**\* Warning: in file strassen.v, library prime.v is required and has not been found in loadpath!
**\* Warning: in file strassen.v, library binomial.v is required and has not been found in loadpath!
**\* Warning: in file strassen.v, library ssralg.v is required and has not been found in loadpath!
**\* Warning: in file strassen.v, library finset.v is required and has not been found in loadpath!
**\* Warning: in file strassen.v, library fingroup.v is required and has not been found in loadpath!
**\* Warning: in file strassen.v, library finalg.v is required and has not been found in loadpath!
**\* Warning: in file strassen.v, library perm.v is required and has not been found in loadpath!
**\* Warning: in file strassen.v, library zmodp.v is required and has not been found in loadpath!
**\* Warning: in file strassen.v, library matrix.v is required and has not been found in loadpath!
/usr/bin/coqdep -c -slash -I .  "karatsuba.v" > "karatsuba.v.d" || ( RV=$?; rm -f "karatsuba.v.d"; exit ${RV} )
**\* Warning: in file karatsuba.v, library ssreflect.v is required and has not been found in loadpath!
**\* Warning: in file karatsuba.v, library ssrfun.v is required and has not been found in loadpath!
**\* Warning: in file karatsuba.v, library ssrbool.v is required and has not been found in loadpath!
**\* Warning: in file karatsuba.v, library eqtype.v is required and has not been found in loadpath!
**\* Warning: in file karatsuba.v, library ssrnat.v is required and has not been found in loadpath!
**\* Warning: in file karatsuba.v, library div.v is required and has not been found in loadpath!
**\* Warning: in file karatsuba.v, library seq.v is required and has not been found in loadpath!
**\* Warning: in file karatsuba.v, library path.v is required and has not been found in loadpath!
**\* Warning: in file karatsuba.v, library choice.v is required and has not been found in loadpath!
**\* Warning: in file karatsuba.v, library fintype.v is required and has not been found in loadpath!
**\* Warning: in file karatsuba.v, library tuple.v is required and has not been found in loadpath!
**\* Warning: in file karatsuba.v, library finset.v is required and has not been found in loadpath!
**\* Warning: in file karatsuba.v, library ssralg.v is required and has not been found in loadpath!
**\* Warning: in file karatsuba.v, library poly.v is required and has not been found in loadpath!
**\* Warning: in file karatsuba.v, library bigop.v is required and has not been found in loadpath!
/usr/bin/coqdep -c -slash -I .  "cseqpolydvd.v" > "cseqpolydvd.v.d" || ( RV=$?; rm -f "cseqpolydvd.v.d"; exit ${RV} )
**\* Warning: in file cseqpolydvd.v, library ssreflect.v is required and has not been found in loadpath!
**\* Warning: in file cseqpolydvd.v, library ssrfun.v is required and has not been found in loadpath!
**\* Warning: in file cseqpolydvd.v, library ssrbool.v is required and has not been found in loadpath!
**\* Warning: in file cseqpolydvd.v, library eqtype.v is required and has not been found in loadpath!
**\* Warning: in file cseqpolydvd.v, library ssrnat.v is required and has not been found in loadpath!
**\* Warning: in file cseqpolydvd.v, library div.v is required and has not been found in loadpath!
**\* Warning: in file cseqpolydvd.v, library seq.v is required and has not been found in loadpath!
**\* Warning: in file cseqpolydvd.v, library path.v is required and has not been found in loadpath!
**\* Warning: in file cseqpolydvd.v, library choice.v is required and has not been found in loadpath!
**\* Warning: in file cseqpolydvd.v, library fintype.v is required and has not been found in loadpath!
**\* Warning: in file cseqpolydvd.v, library tuple.v is required and has not been found in loadpath!
**\* Warning: in file cseqpolydvd.v, library finset.v is required and has not been found in loadpath!
**\* Warning: in file cseqpolydvd.v, library ssralg.v is required and has not been found in loadpath!
**\* Warning: in file cseqpolydvd.v, library poly.v is required and has not been found in loadpath!
/usr/bin/coqdep -c -slash -I .  "cseqpoly.v" > "cseqpoly.v.d" || ( RV=$?; rm -f "cseqpoly.v.d"; exit ${RV} )
**\* Warning: in file cseqpoly.v, library ssreflect.v is required and has not been found in loadpath!
**\* Warning: in file cseqpoly.v, library ssrfun.v is required and has not been found in loadpath!
**\* Warning: in file cseqpoly.v, library ssrbool.v is required and has not been found in loadpath!
**\* Warning: in file cseqpoly.v, library eqtype.v is required and has not been found in loadpath!
**\* Warning: in file cseqpoly.v, library ssrnat.v is required and has not been found in loadpath!
**\* Warning: in file cseqpoly.v, library div.v is required and has not been found in loadpath!
**\* Warning: in file cseqpoly.v, library seq.v is required and has not been found in loadpath!
**\* Warning: in file cseqpoly.v, library path.v is required and has not been found in loadpath!
**\* Warning: in file cseqpoly.v, library choice.v is required and has not been found in loadpath!
**\* Warning: in file cseqpoly.v, library fintype.v is required and has not been found in loadpath!
**\* Warning: in file cseqpoly.v, library tuple.v is required and has not been found in loadpath!
**\* Warning: in file cseqpoly.v, library finset.v is required and has not been found in loadpath!
**\* Warning: in file cseqpoly.v, library ssralg.v is required and has not been found in loadpath!
**\* Warning: in file cseqpoly.v, library poly.v is required and has not been found in loadpath!
**\* Warning: in file cseqpoly.v, library polydiv.v is required and has not been found in loadpath!
/usr/bin/coqdep -c -slash -I .  "polydvd.v" > "polydvd.v.d" || ( RV=$?; rm -f "polydvd.v.d"; exit ${RV} )
**\* Warning: in file polydvd.v, library ssreflect.v is required and has not been found in loadpath!
**\* Warning: in file polydvd.v, library ssrfun.v is required and has not been found in loadpath!
**\* Warning: in file polydvd.v, library ssrbool.v is required and has not been found in loadpath!
**\* Warning: in file polydvd.v, library eqtype.v is required and has not been found in loadpath!
**\* Warning: in file polydvd.v, library ssrnat.v is required and has not been found in loadpath!
**\* Warning: in file polydvd.v, library div.v is required and has not been found in loadpath!
**\* Warning: in file polydvd.v, library seq.v is required and has not been found in loadpath!
**\* Warning: in file polydvd.v, library path.v is required and has not been found in loadpath!
**\* Warning: in file polydvd.v, library choice.v is required and has not been found in loadpath!
**\* Warning: in file polydvd.v, library fintype.v is required and has not been found in loadpath!
**\* Warning: in file polydvd.v, library tuple.v is required and has not been found in loadpath!
**\* Warning: in file polydvd.v, library finset.v is required and has not been found in loadpath!
**\* Warning: in file polydvd.v, library ssralg.v is required and has not been found in loadpath!
**\* Warning: in file polydvd.v, library matrix.v is required and has not been found in loadpath!
**\* Warning: in file polydvd.v, library poly.v is required and has not been found in loadpath!
**\* Warning: in file polydvd.v, library bigop.v is required and has not been found in loadpath!
**\* Warning: in file polydvd.v, library polydiv.v is required and has not been found in loadpath!
/usr/bin/coqdep -c -slash -I .  "rank.v" > "rank.v.d" || ( RV=$?; rm -f "rank.v.d"; exit ${RV} )
**\* Warning: in file rank.v, library ssreflect.v is required and has not been found in loadpath!
**\* Warning: in file rank.v, library ssrfun.v is required and has not been found in loadpath!
**\* Warning: in file rank.v, library ssrbool.v is required and has not been found in loadpath!
**\* Warning: in file rank.v, library eqtype.v is required and has not been found in loadpath!
**\* Warning: in file rank.v, library ssrnat.v is required and has not been found in loadpath!
**\* Warning: in file rank.v, library div.v is required and has not been found in loadpath!
**\* Warning: in file rank.v, library seq.v is required and has not been found in loadpath!
**\* Warning: in file rank.v, library ssralg.v is required and has not been found in loadpath!
**\* Warning: in file rank.v, library fintype.v is required and has not been found in loadpath!
**\* Warning: in file rank.v, library perm.v is required and has not been found in loadpath!
**\* Warning: in file rank.v, library matrix.v is required and has not been found in loadpath!
**\* Warning: in file rank.v, library bigop.v is required and has not been found in loadpath!
**\* Warning: in file rank.v, library zmodp.v is required and has not been found in loadpath!
**\* Warning: in file rank.v, library mxalgebra.v is required and has not been found in loadpath!
/usr/bin/coqdep -c -slash -I .  "seqmatrix.v" > "seqmatrix.v.d" || ( RV=$?; rm -f "seqmatrix.v.d"; exit ${RV} )
**\* Warning: in file seqmatrix.v, library ssreflect.v is required and has not been found in loadpath!
**\* Warning: in file seqmatrix.v, library ssrbool.v is required and has not been found in loadpath!
**\* Warning: in file seqmatrix.v, library ssrfun.v is required and has not been found in loadpath!
**\* Warning: in file seqmatrix.v, library eqtype.v is required and has not been found in loadpath!
**\* Warning: in file seqmatrix.v, library ssrnat.v is required and has not been found in loadpath!
**\* Warning: in file seqmatrix.v, library seq.v is required and has not been found in loadpath!
**\* Warning: in file seqmatrix.v, library choice.v is required and has not been found in loadpath!
**\* Warning: in file seqmatrix.v, library fintype.v is required and has not been found in loadpath!
**\* Warning: in file seqmatrix.v, library div.v is required and has not been found in loadpath!
**\* Warning: in file seqmatrix.v, library finfun.v is required and has not been found in loadpath!
**\* Warning: in file seqmatrix.v, library bigop.v is required and has not been found in loadpath!
**\* Warning: in file seqmatrix.v, library prime.v is required and has not been found in loadpath!
**\* Warning: in file seqmatrix.v, library binomial.v is required and has not been found in loadpath!
**\* Warning: in file seqmatrix.v, library ssralg.v is required and has not been found in loadpath!
**\* Warning: in file seqmatrix.v, library finset.v is required and has not been found in loadpath!
**\* Warning: in file seqmatrix.v, library fingroup.v is required and has not been found in loadpath!
**\* Warning: in file seqmatrix.v, library finalg.v is required and has not been found in loadpath!
**\* Warning: in file seqmatrix.v, library perm.v is required and has not been found in loadpath!
**\* Warning: in file seqmatrix.v, library zmodp.v is required and has not been found in loadpath!
**\* Warning: in file seqmatrix.v, library matrix.v is required and has not been found in loadpath!
/usr/bin/coqdep -c -slash -I .  "Qinfra.v" > "Qinfra.v.d" || ( RV=$?; rm -f "Qinfra.v.d"; exit ${RV} )
**\* Warning: in file Qinfra.v, library ssreflect.v is required and has not been found in loadpath!
**\* Warning: in file Qinfra.v, library ssrbool.v is required and has not been found in loadpath!
**\* Warning: in file Qinfra.v, library eqtype.v is required and has not been found in loadpath!
**\* Warning: in file Qinfra.v, library ssrnat.v is required and has not been found in loadpath!
**\* Warning: in file Qinfra.v, library seq.v is required and has not been found in loadpath!
**\* Warning: in file Qinfra.v, library choice.v is required and has not been found in loadpath!
**\* Warning: in file Qinfra.v, library fintype.v is required and has not been found in loadpath!
**\* Warning: in file Qinfra.v, library finfun.v is required and has not been found in loadpath!
**\* Warning: in file Qinfra.v, library ssrfun.v is required and has not been found in loadpath!
**\* Warning: in file Qinfra.v, library bigop.v is required and has not been found in loadpath!
**\* Warning: in file Qinfra.v, library ssralg.v is required and has not been found in loadpath!
/usr/bin/coqdep -c -slash -I .  "Zinfra.v" > "Zinfra.v.d" || ( RV=$?; rm -f "Zinfra.v.d"; exit ${RV} )
**\* Warning: in file Zinfra.v, library ssreflect.v is required and has not been found in loadpath!
**\* Warning: in file Zinfra.v, library ssrfun.v is required and has not been found in loadpath!
**\* Warning: in file Zinfra.v, library ssrbool.v is required and has not been found in loadpath!
**\* Warning: in file Zinfra.v, library eqtype.v is required and has not been found in loadpath!
**\* Warning: in file Zinfra.v, library ssrnat.v is required and has not been found in loadpath!
**\* Warning: in file Zinfra.v, library div.v is required and has not been found in loadpath!
**\* Warning: in file Zinfra.v, library ssralg.v is required and has not been found in loadpath!
**\* Warning: in file Zinfra.v, library seq.v is required and has not been found in loadpath!
**\* Warning: in file Zinfra.v, library choice.v is required and has not been found in loadpath!
**\* Warning: in file Zinfra.v, library fintype.v is required and has not been found in loadpath!
**\* Warning: in file Zinfra.v, library finfun.v is required and has not been found in loadpath!
**\* Warning: in file Zinfra.v, library bigop.v is required and has not been found in loadpath!
/usr/bin/coqdep -c -slash -I .  "cdvdring.v" > "cdvdring.v.d" || ( RV=$?; rm -f "cdvdring.v.d"; exit ${RV} )
**\* Warning: in file cdvdring.v, library ssreflect.v is required and has not been found in loadpath!
**\* Warning: in file cdvdring.v, library ssrfun.v is required and has not been found in loadpath!
**\* Warning: in file cdvdring.v, library ssrbool.v is required and has not been found in loadpath!
**\* Warning: in file cdvdring.v, library eqtype.v is required and has not been found in loadpath!
**\* Warning: in file cdvdring.v, library ssrnat.v is required and has not been found in loadpath!
**\* Warning: in file cdvdring.v, library div.v is required and has not been found in loadpath!
**\* Warning: in file cdvdring.v, library seq.v is required and has not been found in loadpath!
**\* Warning: in file cdvdring.v, library path.v is required and has not been found in loadpath!
**\* Warning: in file cdvdring.v, library ssralg.v is required and has not been found in loadpath!
**\* Warning: in file cdvdring.v, library fintype.v is required and has not been found in loadpath!
**\* Warning: in file cdvdring.v, library perm.v is required and has not been found in loadpath!
**\* Warning: in file cdvdring.v, library tuple.v is required and has not been found in loadpath!
**\* Warning: in file cdvdring.v, library choice.v is required and has not been found in loadpath!
**\* Warning: in file cdvdring.v, library matrix.v is required and has not been found in loadpath!
**\* Warning: in file cdvdring.v, library bigop.v is required and has not been found in loadpath!
**\* Warning: in file cdvdring.v, library zmodp.v is required and has not been found in loadpath!
**\* Warning: in file cdvdring.v, library mxalgebra.v is required and has not been found in loadpath!
**\* Warning: in file cdvdring.v, library poly.v is required and has not been found in loadpath!
/usr/bin/coqdep -c -slash -I .  "dvdring.v" > "dvdring.v.d" || ( RV=$?; rm -f "dvdring.v.d"; exit ${RV} )
**\* Warning: in file dvdring.v, library ssreflect.v is required and has not been found in loadpath!
**\* Warning: in file dvdring.v, library ssrfun.v is required and has not been found in loadpath!
**\* Warning: in file dvdring.v, library ssrbool.v is required and has not been found in loadpath!
**\* Warning: in file dvdring.v, library eqtype.v is required and has not been found in loadpath!
**\* Warning: in file dvdring.v, library ssrnat.v is required and has not been found in loadpath!
**\* Warning: in file dvdring.v, library div.v is required and has not been found in loadpath!
**\* Warning: in file dvdring.v, library seq.v is required and has not been found in loadpath!
**\* Warning: in file dvdring.v, library path.v is required and has not been found in loadpath!
**\* Warning: in file dvdring.v, library ssralg.v is required and has not been found in loadpath!
**\* Warning: in file dvdring.v, library fintype.v is required and has not been found in loadpath!
**\* Warning: in file dvdring.v, library perm.v is required and has not been found in loadpath!
**\* Warning: in file dvdring.v, library tuple.v is required and has not been found in loadpath!
**\* Warning: in file dvdring.v, library choice.v is required and has not been found in loadpath!
**\* Warning: in file dvdring.v, library matrix.v is required and has not been found in loadpath!
**\* Warning: in file dvdring.v, library bigop.v is required and has not been found in loadpath!
**\* Warning: in file dvdring.v, library zmodp.v is required and has not been found in loadpath!
**\* Warning: in file dvdring.v, library mxalgebra.v is required and has not been found in loadpath!
**\* Warning: in file dvdring.v, library poly.v is required and has not been found in loadpath!
**\* Warning: in file dvdring.v, library generic_quotient.v is required and has not been found in loadpath!
/usr/bin/coqdep -c -slash -I .  "cssralg.v" > "cssralg.v.d" || ( RV=$?; rm -f "cssralg.v.d"; exit ${RV} )
**\* Warning: in file cssralg.v, library ssreflect.v is required and has not been found in loadpath!
**\* Warning: in file cssralg.v, library ssrfun.v is required and has not been found in loadpath!
**\* Warning: in file cssralg.v, library ssrbool.v is required and has not been found in loadpath!
**\* Warning: in file cssralg.v, library eqtype.v is required and has not been found in loadpath!
**\* Warning: in file cssralg.v, library ssrnat.v is required and has not been found in loadpath!
**\* Warning: in file cssralg.v, library div.v is required and has not been found in loadpath!
**\* Warning: in file cssralg.v, library seq.v is required and has not been found in loadpath!
**\* Warning: in file cssralg.v, library path.v is required and has not been found in loadpath!
**\* Warning: in file cssralg.v, library fintype.v is required and has not been found in loadpath!
**\* Warning: in file cssralg.v, library tuple.v is required and has not been found in loadpath!
**\* Warning: in file cssralg.v, library finset.v is required and has not been found in loadpath!
**\* Warning: in file cssralg.v, library ssralg.v is required and has not been found in loadpath!
**\* Warning: in file cssralg.v, library bigop.v is required and has not been found in loadpath!
/usr/bin/coqdep -c -slash -I .  "ssrcomplements.v" > "ssrcomplements.v.d" || ( RV=$?; rm -f "ssrcomplements.v.d"; exit ${RV} )
**\* Warning: in file ssrcomplements.v, library ssreflect.v is required and has not been found in loadpath!
**\* Warning: in file ssrcomplements.v, library ssrfun.v is required and has not been found in loadpath!
**\* Warning: in file ssrcomplements.v, library ssrbool.v is required and has not been found in loadpath!
**\* Warning: in file ssrcomplements.v, library eqtype.v is required and has not been found in loadpath!
**\* Warning: in file ssrcomplements.v, library ssrnat.v is required and has not been found in loadpath!
**\* Warning: in file ssrcomplements.v, library div.v is required and has not been found in loadpath!
**\* Warning: in file ssrcomplements.v, library seq.v is required and has not been found in loadpath!
**\* Warning: in file ssrcomplements.v, library path.v is required and has not been found in loadpath!
**\* Warning: in file ssrcomplements.v, library ssralg.v is required and has not been found in loadpath!
**\* Warning: in file ssrcomplements.v, library fintype.v is required and has not been found in loadpath!
**\* Warning: in file ssrcomplements.v, library finfun.v is required and has not been found in loadpath!
**\* Warning: in file ssrcomplements.v, library perm.v is required and has not been found in loadpath!
**\* Warning: in file ssrcomplements.v, library matrix.v is required and has not been found in loadpath!
**\* Warning: in file ssrcomplements.v, library bigop.v is required and has not been found in loadpath!
**\* Warning: in file ssrcomplements.v, library zmodp.v is required and has not been found in loadpath!
**\* Warning: in file ssrcomplements.v, library mxalgebra.v is required and has not been found in loadpath!
**\* Warning: in file ssrcomplements.v, library choice.v is required and has not been found in loadpath!
**\* Warning: in file ssrcomplements.v, library poly.v is required and has not been found in loadpath!
**\* Warning: in file ssrcomplements.v, library polydiv.v is required and has not been found in loadpath!
**\* Warning: in file ssrcomplements.v, library mxpoly.v is required and has not been found in loadpath!
**\* Warning: in file ssrcomplements.v, library binomial.v is required and has not been found in loadpath!
make[1]: Leaving directory `/home/martin/geo/CoqEAL/v0.1'
make[1]: ocamlc.opt: Command not found
make[1]: Entering directory`/home/martin/geo/CoqEAL/v0.1'
make[1]: Nothing to be done for `Makefile'.
make[1]: Leaving directory`/home/martin/geo/CoqEAL/v0.1'
/bin/mkdir -p bin
make -f Makefile.coq all
make[1]: ocamlc.opt: Command not found
make[1]: Entering directory `/home/martin/geo/CoqEAL/v0.1'
/usr/bin/coqc  -q  -I .    ssrcomplements
File "./ssrcomplements.v", line 3, characters 0-67:
Error: Cannot find library ssreflect in loadpath
make[1]: *** [ssrcomplements.vo] Error 1
make[1]: Leaving directory`/home/martin/geo/CoqEAL/v0.1'
make: **\* [all] Error 2
martin@ubuntu:~/geo/CoqEAL/v0.1$ export COQBIN=/usr/bin/
martin@ubuntu:~/geo/CoqEAL/v0.1$ export SSRSRC=/home/martin/geo/CoqEAL/theory/
martin@ubuntu:~/geo/CoqEAL/v0.1$ export SSRLIB=/home/martin/geo/CoqEAL/
martin@ubuntu:~/geo/CoqEAL/v0.1$ make
make -f Makefile.coq Makefile
make[1]: ocamlc.opt: Command not found
make[1]: Entering directory `/home/martin/geo/CoqEAL/v0.1'
make[1]: Nothing to be done for`Makefile'.
make[1]: Leaving directory `/home/martin/geo/CoqEAL/v0.1'
/bin/mkdir -p bin
make -f Makefile.coq all
make[1]: ocamlc.opt: Command not found
make[1]: Entering directory`/home/martin/geo/CoqEAL/v0.1'
/usr/bin/coqc  -q  -I .    ssrcomplements
File "./ssrcomplements.v", line 3, characters 0-67:
Error: Cannot find library ssreflect in loadpath
make[1]: **\* [ssrcomplements.vo] Error 1
make[1]: Leaving directory `/home/martin/geo/CoqEAL/v0.1'
make: **\* [all] Error 2
martin@ubuntu:~/geo/CoqEAL/v0.1$

martin@ubuntu:~/geo/CoqEAL/theory$ which coq
martin@ubuntu:~/geo/CoqEAL/theory$
martin@ubuntu:~/geo/CoqEAL$ pwd
/home/martin/geo/CoqEAL

martin@ubuntu:~/geo/CoqEAL/v0.1$ coqc -v
The Coq Proof Assistant, version 8.3pl4 (April 2012)
compiled on Apr 03 2012 10:32:56 with OCaml 3.12.1

export COQBIN=/usr/bin/coqc
export SSRSRC=/home/martin/geo/CoqEAL/theory
export SSRLIB=/home/martin/geo/CoqEAL

martin@ubuntu:~/geo/CoqEAL/v0.1$ make
/usr/bin/coqccoq_makefile -f Make  -o Makefile.coq
make: /usr/bin/coqccoq_makefile: Command not found
make: **\* [Makefile.coq] Error 127

martin@ubuntu:~/geo/CoqEAL/theory$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.4 LTS
Release:    12.04
Codename:   precise

In order to compile this library, you have to set three environment variables:
- COQBIN should be the path to Coq's binaries (coqc, coqdep,...)
- SSRSRC should be the path to the ssreflect "src" folder
  (in which ssreflect.cmxs can be found).
- SSRLIB should be the path to ssr theories (where the .vo files are)

To set environment variables, you may use a command like:
export SSRSRC=/path/...

and then type `make` to compile

**Comment by CohenCyril** [comment]
I guess this issue is now outdated?

**Comment by hoyeunglee** [comment]
Please close case
