### ISSUE TITLE
Dependencies of CoqEAL with Coq 8.10.1

### ISSUE THREAD

**Issue by amahboubi** [CoqEAL/CoqEAL#23]
I have trouble compiling CoqEAL with Coq 8.10.1 and Mathematical Components 1.9. And more precisely I have trouble finding the right dependencies:

- I had to add a `no-template-check` option to `coqtop` in the Makfile in order to compile refinements/param.v This seems consistent with the current test-suite of coq-param, but is a bit unfortunate isn't it? @proux01 is it the right thing to do?

- `multinomials` is in the dependencies, which itself depend on `finmap`. But `finmap` does not seem to tag a specific version for Coq 8.10.1+ MathComp 1.9 So I tried `1.3.4`. But then `multinomials` does not compile. 

Is there a way to get all this to work (possibly at the price of the `no-template-check` option)? If so could you document it and tag the right versions in the corresponding repos, including this one?

**Comment by amahboubi** [comment]
See my problem with multinomials [here](https://github.com/math-comp/multinomials/issues/29).

**Comment by proux01** [comment]
> * I had to add a `no-template-check` option to `coqtop` in the Makfile in order to compile refinements/param.v This seems consistent with the current test-suite of coq-param, but is a bit unfortunate isn't it? @proux01 is it the right thing to do?

This has been fixed https://github.com/coq-community/paramcoq/commit/7b4ed44960476e858390e775d3d2dcd563784595 and is included in coq-paramcoq.1.1.2 which is required by coq-coqeal.1.0.1 the only version compatible with Coq 8.10.

So there seems to be something I don't understand there. Which version of coq-paramcoq and coq-coqeal are you using?

**Comment by amahboubi** [comment]
@proux01 thanks for the update. I am using the latest commit of the v8.10 branch of coq-paramcoq.

**Comment by proux01** [comment]
That should work.

However, may I suggest to use Opam:
```
opam update
opam install coq-coqeal
```
should get you CoqEAL installed with Coq 8.10.1 and Mathcomp 1.9.0 (provided these are the versions installed in the current Opam switch).

**Comment by amahboubi** [comment]
I would like to avoid using opam, if possible.

Isn't it the case that the commit you mention is on the master and v8.11 branches, not on v8.10?

**Comment by proux01** [comment]
Then the following works for me:
```
% coqc --version
The Coq Proof Assistant, version 8.10.1 (November 2019)
compiled on Nov 4 2019 19:33:06 with OCaml 4.05.0
# I also have Mathcomp 1.9.0
% git checkout https://github.com/coq/bignums.git
% cd bignums
% git checkout v8.10
% git clean -dxf
% make -j2
% make install
% cd ..
% git clone https://github.com/coq-community/paramcoq.git
% git checkout v8.10
% git clean -dxf
% make -j2
% make install
% cd ..
# Install mathcomp multinomials 1.3 (https://github.com/math-comp/multinomials/releases)
# and finmap 1.2.1 (https://github.com/math-comp/finmap/releases)
% git clone https://github.com/CoqEAL/CoqEAL.git
% cd CoqEAL
% git checkout master
% git clean -dxf
% make -j2
% make install
```

But using Opam seems just way easier.

**Comment by amahboubi** [comment]
Ok I am cleaning everything except Coq and mathcomp and start anew.

(Opam is not that convenient for developing multiple layers of libraries. I stopped using it because I had not enough control and in particular spent too much time re-compiling things).

**Comment by proux01** [comment]
Well, color and tastes.

I personally find it convenient to have multiple switches to easily test things with various versions of Coq for instance. And when I'm unsure what version of some library I have, `opam show library` just tells me.

**Comment by amahboubi** [comment]
Many thanks, it did work. In the end, the only change I made was to downgrade `finmap` (the latest release is 1.3.4).
And it seems my v8.10 branch was not up to date. Sorry for the noise.

Regarding opam: often what I want to test is not different versions of Coq but rather different versions of Coq libaries (typically MathComp), on top on which I am developing further projects. 

After a few months experimenting, it seems `nix-shell` is better suited to my needs. 

But it is true that sometimes being away from opam has a cost . Like today.

**Comment by amahboubi** [comment]
Thanks again @proux01 : the issue is solved:
- I did not take into account a recent commit in CoqEAL fixing the template check isse
- the right version of `finmap` to be used is 1.2.

**Comment by proux01** [comment]
> the issue is solved:

Glad to hear it

> * I did not take into account a recent commit in CoqEAL fixing the template check problem

I guess you mean in paramcoq? If possible, you should, `-no-template-check` is unsound (note that if you compiled the v8.10 branch of paramcoq, the said commit in included in it and you are fine).

**Comment by proux01** [comment]
> After a few months experimenting, it seems `nix-shell` is better suited to my needs.

Maybe should I give it a try one day.

> But it is true that sometimes being away from opam has a cost . Like today.

Sure, but even without using it, it's still possible to extract information from it. The finmap 1.2.1 requirement can be found here for instance : https://github.com/coq/opam-coq-archive/blob/master/released/packages/coq-mathcomp-multinomials/coq-mathcomp-multinomials.1.3/opam

**Comment by amahboubi** [comment]
Yes, thanks for the tip. 
That mistake of mine came from a misunderstanding of a private communication with @CohenCyril. Again, thanks a lot for the swift feedback and help.
